/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getBalance' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUser' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'id' : IDL.Nat,
            'balance' : IDL.Nat,
            'name' : IDL.Text,
            'mobile' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'id' : IDL.Nat,
            'balance' : IDL.Nat,
            'name' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'id' : IDL.Nat,
            'balance' : IDL.Nat,
            'name' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getBalance' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUser' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'id' : IDL.Nat,
              'balance' : IDL.Nat,
              'name' : IDL.Text,
              'mobile' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'id' : IDL.Nat,
              'balance' : IDL.Nat,
              'name' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'id' : IDL.Nat,
              'balance' : IDL.Nat,
              'name' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };